import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<link rel="icon" href="./favicon.ico" />
			</head>
			<script
				async
				defer
				src="https://static.cdn.prismic.io/prismic.js?new=true&repo=neelanjans-profile"
			></script>
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
				disableTransitionOnChange
			>
				<body
					className={cn(
						"bg-background font-sans antialiased",
						fontSans.variable
					)}
				>
					<Analytics />
					<SpeedInsights />
					<Header />
					{children}
					<Footer />
				</body>
			</ThemeProvider>
		</html>
	);
}
